Algeria:
  IPv4: []
  IPv6: []
Argentina:
  IPv4: []
  IPv6: []
Australia:
  IPv4: []
  IPv6: []
Bolivia:
  IPv4: []
  IPv6: []
Brazil:
  IPv4: []
  IPv6: []
Canada:
  IPv4: []
  IPv6: []
Chile:
  IPv4: []
  IPv6: []
Colombia:
  IPv4: []
  IPv6: []
Costa Rica:
  IPv4: []
  IPv6: []
Cuba:
  IPv4: []
  IPv6: []
Dominican Republic:
  IPv4: []
  IPv6: []
Ecuador:
  IPv4: []
  IPv6: []
Egypt:
  IPv4: []
  IPv6: []
Ethiopia:
  IPv4: []
  IPv6: []
Fiji:
  IPv4: []
  IPv6: []
France:
  IPv4: []
  IPv6: []
Germany:
  IPv4: []
  IPv6: []
Ghana:
  IPv4: []
  IPv6: []
Guatemala:
  IPv4: []
  IPv6: []
Honduras:
  IPv4: []
  IPv6: []
Hong Kong:
  IPv4: []
  IPv6: []
India:
  IPv4: []
  IPv6: []
Iran:
  IPv4: []
  IPv6: []
Iraq:
  IPv4: []
  IPv6: []
Israel:
  IPv4: []
  IPv6: []
Italy:
  IPv4: []
  IPv6: []
Jamaica:
  IPv4: []
  IPv6: []
Japan:
  IPv4: []
  IPv6: []
Jordan:
  IPv4: []
  IPv6: []
Kenya:
  IPv4: []
  IPv6: []
Kuwait:
  IPv4: []
  IPv6: []
Malaysia:
  IPv4: []
  IPv6: []
Mexico:
  IPv4: []
  IPv6: []
Morocco:
  IPv4: []
  IPv6: []
Nauru:
  IPv4: []
  IPv6: []
New Zealand:
  IPv4: []
  IPv6: []
Nigeria:
  IPv4: []
  IPv6: []
Panama:
  IPv4: []
  IPv6: []
Papua New Guinea:
  IPv4: []
  IPv6: []
Paraguay:
  IPv4: []
  IPv6: []
Peru:
  IPv4: []
  IPv6: []
Philippines:
  IPv4: []
  IPv6: []
Poland:
  IPv4: []
  IPv6: []
Qatar:
  IPv4: []
  IPv6: []
Russia:
  IPv4: []
  IPv6: []
Saudi Arabia:
  IPv4: []
  IPv6: []
Senegal:
  IPv4: []
  IPv6: []
Singapore:
  IPv4: []
  IPv6: []
Solomon Islands:
  IPv4: []
  IPv6: []
South Africa:
  IPv4: []
  IPv6: []
South Korea:
  IPv4: []
  IPv6: []
Spain:
  IPv4: []
  IPv6: []
Sweden:
  IPv4: []
  IPv6: []
Switzerland:
  IPv4: []
  IPv6: []
Taiwan:
  IPv4: []
  IPv6: []
Tanzania:
  IPv4: []
  IPv6: []
Thailand:
  IPv4: []
  IPv6: []
Tonga:
  IPv4: []
  IPv6: []
Tuvalu:
  IPv4: []
  IPv6: []
United Arab Emirates:
  IPv4: []
  IPv6: []
United Kingdom:
  IPv4: []
  IPv6: []
United States:
  IPv4: []
  IPv6: []
Uruguay:
  IPv4: []
  IPv6: []
Vanuatu:
  IPv4: []
  IPv6: []
Venezuela:
  IPv4: []
  IPv6: []
Vietnam:
  IPv4: []
  IPv6: []
Wallis and Futuna:
  IPv4: []
  IPv6: []
