name: Extract CIDR for Specific Regions

on:
  schedule:
    # 每12小时运行一次
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  extract_cidr:
    runs-on: ubuntu-latest

    steps:
    # 检出仓库代码
    - name: Checkout repository
      uses: actions/checkout@v2

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # 安装依赖
    - name: Install Dependencies
      run: |
        pip install maxminddb

    # 下载 GeoLite2 数据库
    - name: Download GeoLite2-Country.mmdb
      run: |
        wget -O GeoLite2-Country.mmdb https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-Country.mmdb

    # 运行 CIDR 提取脚本
    - name: Run CIDR Extraction Script
      run: |
        python extract_cidr.py

    # 提交并推送更改
    - name: Commit and push changes
      if: success() # 仅在上一步成功时运行
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./Clash/*.txt
        git commit -m "Auto-update IP CIDR files"
        git push
