name: Find Cloudflare CIDR by Country

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *" # 每12小时运行一次

jobs:
  find-cloudflare-cidr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install geoip2 netaddr

    - name: Download MaxMind GeoLite2 Databases
      run: |
        wget https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-ASN.mmdb -O GeoLite2-ASN.mmdb
        wget https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-Country.mmdb -O GeoLite2-Country.mmdb

    - name: Run script to find Cloudflare CIDR
      run: |
        python3 find_overlaps.py

    - name: Commit and push the results
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add outputs/*
        git commit -m "Update Cloudflare CIDR files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
