name: Update IP Lists

on:
  schedule:
    - cron: '0 12 * * *' # 每天定时运行
  push:
    branches:
      - main # 在 main 分支上推送时运行
  workflow_dispatch: # 手动触发

jobs:
  update-lists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Download chnroute_v6.txt
        run: wget -O chnroute_v6.txt https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute_v6.txt

      - name: Check chnroute_v6.txt
        run: |
          if [ ! -f "chnroute_v6.txt" ]; then
            echo "chnroute_v6.txt not found!"
            exit 1
          else
            echo "chnroute_v6.txt downloaded successfully:"
            cat chnroute_v6.txt
          fi

      - name: Download CN-ip-cidr.txt
        run: wget -O CN-ip-cidr.txt https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt

      - name: Check CN-ip-cidr.txt
        run: |
          if [ ! -f "CN-ip-cidr.txt" ]; then
            echo "CN-ip-cidr.txt not found!"
            exit 1
          else
            echo "CN-ip-cidr.txt downloaded successfully:"
            cat CN-ip-cidr.txt
          fi

      - name: Process chnroute_v6.txt
        run: |
          python -c "import sys; \
try: \
    with open('chnroute_v6.txt', 'r') as file: \
        lines = file.readlines(); \
    with open('chnroute_v6.list', 'w') as outfile: \
        for line in lines: \
            outfile.write(f'IP-CIDR6,{line.strip()},no-resolve\n'); \
except Exception as e: \
    print(e); \
    sys.exit(1)"

      - name: Process CN-ip-cidr.txt
        run: |
          python -c "import sys; \
try: \
    with open('CN-ip-cidr.txt', 'r') as file: \
        lines = file.readlines(); \
    with open('CN-ip-cidr.list', 'w') as outfile: \
        for line in lines: \
            outfile.write(f'IP-CIDR,{line.strip()},no-resolve\n'); \
except Exception as e: \
    print(e); \
    sys.exit(1)"

      - name: Commit and push changes
        run: |
          git config --global user.name '${{ secrets.GIT_USER }}'
          git config --global user.email '${{ secrets.GIT_EMAIL }}'
          git add chnroute_v6.list CN-ip-cidr.list
          git commit -m 'Update IP lists'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
