name: Update IP CIDR Files

on:
  schedule:
    - cron: '0 */12 * * *' # 每12小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
    - name: 检查出当前仓库
      uses: actions/checkout@v3

    - name: 下载并处理 chnroute_v6.txt
      run: |
        curl -s https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute_v6.txt | \
        sed 's/^/IP-CIDR6,/' | sed 's/$/,no-resolve/' > CN-IPv6-cidr.list

    - name: 下载并处理 chnroute.txt
      run: |
        curl -s https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute.txt | \
        sed 's/^/IP-CIDR,/' | sed 's/$/,no-resolve/' > CN-IPv4-cidr.list

    - name: 下载并处理 CloudflareCIDR-v6.txt
      run: |
        curl -s https://raw.githubusercontent.com/GuangYu-yu/ACL4SSR/main/Clash/CloudflareCIDR-v6.txt | \
        sed 's/^/IP-CIDR6,/' | sed 's/$/,no-resolve/' > CloudflareCIDR-v6.list

    - name: 下载并处理 CloudflareCIDR.txt
      run: |
        curl -s https://raw.githubusercontent.com/GuangYu-yu/ACL4SSR/main/Clash/CloudflareCIDR.txt | \
        sed 's/^/IP-CIDR,/' | sed 's/$/,no-resolve/' > CloudflareCIDR.list

    - name: 检查是否有更改
      run: |
        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        fi

    - name: 提交并推送更改
      if: success() # 仅在上一步成功时运行
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -m "Auto-update IP CIDR files"
        git push
