name: Delete TXT Files

on:
  workflow_dispatch:

jobs:
  delete_txt_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files before deletion
        run: ls -l

      - name: Delete TXT files
        run: |
          find . -maxdepth 1 -name "*.txt" -type f -exec rm {} +

      - name: List files after deletion
        run: ls -l
