name: 提取地区-CIDR

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch: 

jobs:
  extract_cidr:
    runs-on: ubuntu-latest 

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          pip install maxminddb

      - name: 下载 GeoLite2-Country.mmdb
        run: |
          wget -O GeoLite2-Country.mmdb https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-Country.mmdb

      - name: 运行 CIDR 提取脚本
        run: |
          python 提取地区-CIDR.py

      - name: 打印当前工作目录
        run: |
          pwd

      - name: 检查文件更改
        id: check_files
        run: |
          git diff --exit-code || echo "::set-output name=changed::true"

      - name: 提交并推送更改
        if: steps.check_files.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./Global/*.txt
          git commit -m "自动更新 IP CIDR 文件" || echo "没有需要提交的更改"
          git push
