name: 获取Cloudflare各地区CIDR

# 触发器：手动或定时
on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: "0 */12 * * *"  # 每 12 小时运行一次

jobs:
  compare-cidrs:  # 任务名称
    runs-on: ubuntu-latest  # 在最新的 Ubuntu 环境上运行
    steps:
      - name: 检出代码  # 拉取 GitHub 仓库中的代码
        uses: actions/checkout@v3  # 使用 checkout v3 版本

      - name: 设置 Python 环境  # 配置 Python 运行环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # 使用 Python 3.x 版本

      - name: 安装依赖  # 安装必要的 Python 包
        run: pip install netaddr requests  # 安装 netaddr 和 requests 库

      - name: 运行 CIDR 比较脚本  # 执行 Python 脚本
        run: python compare_cidr.py

      - name: 提交并推送更改  # 将修改后的文件提交并推送到仓库
        if: success()  # 如果上一步成功，则执行此步骤
        run: |
          git config --global user.name 'github-actions[bot]'  # 配置 Git 用户名
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'  # 配置 Git 用户邮箱
          git add Cloudflare-*.txt  # 添加所有以 Cloudflare 开头的文件
          git commit -m "自动更新 Cloudflare CIDR 文件"  # 提交修改
          git push  # 推送到远程仓库
